server:
  port: 3000

debug: false
management.endpoints.web.exposure.include: "*"

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:/test
    username: sa

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

  data.rest:
    base-path: /api
    detection-strategy: annotated
  sql:
    init:
      mode: always

---

